FROM node:22-alpine AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS dependencies
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_LEGAL_OPERATOR_NAME
ARG NEXT_PUBLIC_LEGAL_OPERATOR_DOCUMENT
ARG NEXT_PUBLIC_LEGAL_OPERATOR_ADDRESS
ARG NEXT_PUBLIC_PRIVACY_EMAIL
ARG NEXT_PUBLIC_LEGAL_TERMS_VERSION
ARG NEXT_PUBLIC_LEGAL_PRIVACY_VERSION

ENV NEXT_PUBLIC_LEGAL_OPERATOR_NAME=$NEXT_PUBLIC_LEGAL_OPERATOR_NAME \
    NEXT_PUBLIC_LEGAL_OPERATOR_DOCUMENT=$NEXT_PUBLIC_LEGAL_OPERATOR_DOCUMENT \
    NEXT_PUBLIC_LEGAL_OPERATOR_ADDRESS=$NEXT_PUBLIC_LEGAL_OPERATOR_ADDRESS \
    NEXT_PUBLIC_PRIVACY_EMAIL=$NEXT_PUBLIC_PRIVACY_EMAIL \
    NEXT_PUBLIC_LEGAL_TERMS_VERSION=$NEXT_PUBLIC_LEGAL_TERMS_VERSION \
    NEXT_PUBLIC_LEGAL_PRIVACY_VERSION=$NEXT_PUBLIC_LEGAL_PRIVACY_VERSION

RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
